### PR TITLE
Multiple Backlogs should be splitted into individual Attachment

### PR DESCRIPTION
**Pull request by KongZ**
This PR will refactor code to send Slack alarm/output to proper Slack message guidelines
https://api.slack.com/docs/message-guidelines

### Changes
* Backlogs will not be sent as `text` but it will be send as attachment.
* When multiple backlogs are alarm, each backlog will be separated into individual attachment. Original version was concat as single paragraph.
* Add footer text, footer icon and timestamp on attachment. Footer text also accept field variable. So we can use field as footer text e.g. ${source}
* Custom fields will be included in attachment as attachment fields. Original version was concat into single attachment field.
* Short mode is now worked as Slack short mode. Original version was not working on Alarm.
* Rename `add_attachment` field to `add_stream_info`. Because this setting will only include/exclude stream info.

This PR is a part of huge improvment of Graylog Slack plugin. More PR with new features will be submitted separately after this PR is included.

### CODE REVIEW

**Comment by Aenima4six2** [comment]
@KongZ You still interested in merging your features in ?

**Comment by KongZ** [comment]
@Aenima4six2 I developed a plugin to use with my company. I found Graylog is very useful and I would like contribute back. The plugin has been developed and evolved quite long from the beginning. It might hard to create a small PR now.

You can check out the latest version here https://github.com/omise/graylog-plugin-slack

**Comment by Aenima4six2** [comment]
@KongZ Do you intend to resolve and merge this PR? If not, I'd like to close it.

**Comment by Aenima4six2** [comment]
@KongZ I cannot because there are conflicts needing resolution. If you fix the issues I’ll be happy to evaluate the code for merge consideration.

**Comment by KongZ** [comment]
This gonna be a while before I can resolve them cause #39 already rewrite most of code in the plugin.

**Comment by Aenima4six2** [comment]
That’s fine. I’m going to close this PR. Please reopen or create a new one when you are ready to move forward.

**Pull request closed without merging**
