### PR TITLE
Log a direct link to the graylog message

### PR DESCRIPTION
**Pull request by johshoff**
A link to the stream is useful, but it's even more useful to be able to get
directly to the message. This is especially true if you are looking at an older
message that's outside of the time window given.

This commit misses one thing: referencing the correct index. Hopefully that can
be fixed before a merge. In the meantime I'm using `graylog_deflector`, which
will the index active at the time of using the URL.

I would love some help on how to get the current index. As mentioned in the
code comment, using `msg.getFieldAs(String.class, "_index")` gave me `null`.

### CODE REVIEW

**Comment by johshoff** [comment]
Undid a change that wasn't meant to make it upstream. If we figure out the index name, I can squash it all into one beautiful little commit 😄

**Comment by towolf** [comment]
@joschi could you have a look and help out with getting the index the message is in?

Being able to find the exact message is way more useful than the coarse `/messages?q=*&rangetype=relative&relative=3600` link.

**Comment by patcable** [comment]
This looks like what I had wanted with #35. Started digging into this today with @theunforgiven and we too wondered how to even get the index out of an entry

**Comment by johshoff** [comment]
Anything I can do to move this pull request forward?

**Comment by nenadstojanovikj** [comment]
Is it possible to get this merged?

**Comment by sergiughf** [comment]
What's holding this?

**Comment by johshoff** [comment]
I'm not sure what's holding it. I did have a question about getting the current index instead of using `graylog_deflector`, however I've been using this patch since I wrote it without problem. Perhaps it should be merged as is and then we can work on getting the correct index as a separate issue.

**Comment by Aenima4six2** [comment]
@johshoff I'm taking over the repo maintenance now. We can def get this moving forward. Can you post a sample message of what your patch adds please ? Also, templated messages have been merged in, which removed a lot of old options that are no longer needed. I'd like to add this feature as a first class template variable. Thoughts ?

**Comment by johshoff** [comment]
Great news!

It simply changes "New message" in the graylog message from plain text to a link directly to the log message. It looks like this before and after:

image

I think adding it as a template is a good idea. I won't have time to do that work immediately, so feel free to do it. Otherwise I can try to get around to it at some point.

**Comment by Aenima4six2** [comment]
@johshoff , i can merge this as soon as the conflicts are resolved.

**Comment by johshoff** [comment]
@Aenima4six2 Thanks. Finally got around to merging it. Github didn't like the way I merged, so is displaying all intermediate commits. I created a new pull request with exactly the same code that displays nicer: #60 . Feel free to close one of them and merge the other.

**Pull request merged**
