### PR TITLE
Feature/improve slack plugin

### PR DESCRIPTION
**Pull request by KongZ**
## New
 * Add `footer` text field
 * Add `footer_icon` field
 * Add `timestamp` field
 * Add `add_stream_info` flag to include/exclude stream info
 * Add `notify_users` allows to notify to channel, user or user which name is extracted from fields.

## Changes
 * Merge `iconUrl` and `iconEmoji` into single field. 
 * Remove word `Details` prefix from `pretext` 
 * Do not include backlog item when a value of backlog item setting less than 1
 * When multiple backlog items are included, it will be grouped with attachment field.
 * Remove `add_attachment` flag. Backlog item will be included when setting value is greater than 0
 * Short mode in Alert message will now use Slack short mode.
 * Custom fields will be sent as attachment fields.
 * Replace `notify_channel` flag with `notify_users` text

### CODE REVIEW

**Comment by joschi** [comment]
@KongZ Thanks for your contribution!

Please don't create one big PR with lots of changes but create smaller PRs with small and incremental changes each. This will simplify reviewing these changes.

**Comment by KongZ** [comment]
@joschi Sorry about this. This is a big updated in Slack plugin with a lot of dependencies on each class/field. Is it possible to review? Or should I close it and try to break down into small issues?

**Comment by joschi** [comment]
@KongZ Please break it down into smaller PRs.

**Comment by KongZ** [comment]
Move to #44 and others

**Pull request closed without merging**
